### ISSUE TITLE
How to trigger next datepicker?

### ISSUE THREAD

**Issue by DasomCho** [hevyweb/hw.datepicker#12]
I want to add interaction between 2 datepickers.
How can I trigger next datepicker after select the date on first datepicker? not click second datepicker trigger!

**Comment by hevyweb** [comment]
You should add an event **onSelect** for the first datepicker. Here is an example
```javascript

var datePicker1 = new DatePicker({
  input: $('#hw_example_input1'),
  trigger: $('#hw_example_button1'),
  events: {
    onSelect: function(e){
      setTimeout(function(){
        datePicker2.open();
      }, 0);
    }
  }
});

var datePicker2 = new DatePicker({
  input: $('#hw_example_input2'),
  trigger: $('#hw_example_button2')
});
datePicker1.init();
datePicker2.init();
```
**onSelect** event starts before actual selection. To make it work after date section you should user setTimeout with zero otherwise focus won't jump to the second datepicker however it will be opened.

Did I answered your question?
